import type {Metadata} from "next"
import {Noto_Sans_Myanmar} from "next/font/google"
import "./globals.css"
import Layout from "@/ui/Layout"

const notomm = Noto_Sans_Myanmar({subsets: ["myanmar"], weight: "400"})

export const metadata: Metadata = {
    title: "Birds",
    description: "Generated by create next app",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <head>
                <link rel="shortcut icon" href="/logo.png" type="image/png" />
            </head>
            <body className={notomm.className}>
                <Layout>{children}</Layout>
            </body>
        </html>
    )
}
